DROP TABLE INVOICE;
DROP TABLE COMPANY;

CREATE TABLE COMPANY (id INT PRIMARY KEY IDENTITY, company_name NVARCHAR(40) NOT NULL, city NVARCHAR(40) NOT NULL, country NVARCHAR(40) NOT NULL, nip NCHAR(11) NOT NULL)
CREATE TABLE INVOICE(id INT PRIMARY KEY, company_id INT NOT NULL, date_start DATETIME NOT NULL, date_end DATETIME, netto NVARCHAR(12) NOT NULL, brutto NVARCHAR(12) NOT NULL, tax NCHAR(4) NOT NULL)

SET IDENTITY_INSERT COMPANY ON

ALTER TABLE INVOICE ADD CONSTRAINT invoice_company_id FOREIGN KEY (company_id) REFERENCES company(company_id)
--SELECT * FROM INVOICE

--IF OBJECT_ID('woodDB.Shipment') IS NOT NULL
--BEGIN
--	DROP TABLE Shipment
--END
--GO
--
--IF OBJECT_ID('woodDB.OrderItem') IS NOT NULL
--BEGIN
--	DROP TABLE OrderItem
--END
--GO
--
--IF OBJECT_ID('woodDB.Item') IS NOT NULL
--BEGIN
--	DROP TABLE Item
--END
--GO
--
--IF OBJECT_ID('woodDB.COrder') IS NOT NULL
--BEGIN
--	DROP TABLE COrder
--END
--GO
--
--IF OBJECT_ID('woodDB.Subunit') IS NOT NULL
--BEGIN
--	DROP TABLE Subunit
--END
--GO
--
--IF OBJECT_ID('woodDB.Invoice') IS NOT NULL
--BEGIN
--	DROP TABLE Invoice
--END
--GO
--
--IF OBJECT_ID('woodDB.Company') IS NOT NULL
--BEGIN
--	DROP TABLE Company
--END
--GO
--

--CREATE TABLE COrder ( OrderId INT NOT NULL IDENTITY CONSTRAINT PK_OrderId PRIMARY KEY,InvoiceId INT NOT NULL CONSTRAINT FK_ORDER_INVOICE FOREIGN KEY REFERENCES Invoice(InvoiceId),OrderDate DATE NOT NULL,Currency_Code VARCHAR(3) NOT NULL,Discount VARCHAR(4),TotalBrutto VARCHAR(12) NOT NULL)
--
--CREATE TABLE Item
--(
--	ItemId INT NOT NULL IDENTITY
--		CONSTRAINT PK_ItemId PRIMARY KEY,
--	ItemName NVARCHAR(30) NOT NULL,
--	ItemDescription NVARCHAR(100),
--	Price NCHAR(5) NOT NULL,
--	NumberInStock INT NOT NULL
--)
--
--CREATE TABLE OrderItem
--(
--	OrderId INT NOT NULL IDENTITY
--		CONSTRAINT FK_OrderItem_Order FOREIGN KEY
--		REFERENCES COrder(OrderId),
--	ItemId INT NOT NULL
--		CONSTRAINT FK_OrderItem_Item FOREIGN KEY
--		REFERENCES Item(ItemId),
--	Quantity INT NOT NULL
--)
--
--CREATE TABLE Subunit
--(
--	SubunitId INT NOT NULL IDENTITY PRIMARY KEY,
--	CompanyId INT NOT NULL
--		CONSTRAINT FK_Shipment_Company FOREIGN KEY
--		REFERENCES Company(CompanyId),
--	Country NVARCHAR(40) NOT NULL,
--	City NVARCHAR(40) NOT NULL,
--	Postcode NVARCHAR(12) NOT NULL,
--	Street NVARCHAR(30) NOT NULL
--)
--
--CREATE TABLE Shipment
--(
--	ShipmentId INT NOT NULL IDENTITY
--		CONSTRAINT PK_Shipment PRIMARY KEY,
--	OrderId INT NOT NULL
--		CONSTRAINT FK_Shipment_Order FOREIGN KEY
--		REFERENCES COrder(OrderId),
--	SubunitId INT NOT NULL
--		CONSTRAINT FK_Shipment_Subunit FOREIGN KEY
--		REFERENCES Subunit(SubunitId)
--)